# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  limit:
    description: |
      Limit the total metrics in the cache at one time. Will reject a push if cache is full.
      Default is -1 which is no limit. (default -1)
    type: int
    default: -1
  scrape-timeout:
    description: |
      Timeout for scrape calls. Default is 10 (default 10)
    type: int
    default: 10
