name: Upload charm to charmhub

on:
  push

jobs:
  charmhub-upload:
    runs-on: ubuntu-latest
    name: Charmhub upload
    steps:
      - uses: actions/checkout@v2

      - uses: canonical/charmhub-upload-action@0.2.1
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          upload-image: "false"
