name: Upload charm to charmhub

on:
  push:
    branches:
      - "main"

jobs:
  charmhub-upload:
    runs-on: ubuntu-20.04
    name: Charmhub upload
    steps:
      - uses: actions/checkout@v2

      - uses: canonical/charmhub-upload-action@2.2.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          upload-image: "false"
